---
title: ""
author: ""
date: ""
output: 
  pdf_document:
    includes:
      in_header: "/home/shared-psychosis/Landing Zone/header.tex"
    keep_tex: true
header-includes:
  - \renewcommand{\mytitle}{SnazzieR Example Tables}
---
\thispagestyle{firstpage}
\UNsection{\mytitle}{1.5}

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, dev = "cairo_pdf")
```

## Imports
```{r message=FALSE, warning=FALSE}
library(ggplot2)
library(dplyr)
library(gridExtra)
library(grid)
library(snazzieR)
library(kableExtra)
```

## Iris Data Analysis

**Source:**
Fisher, R. (1936). Iris [Dataset]. UCI Machine Learning Repository. \url{https://doi.org/10.24432/C56C76}.

```{r}
data(iris)
x.iris <- iris[, c("Sepal.Length", "Sepal.Width")]
y.iris <- iris[, c("Petal.Length", "Petal.Width")]
x.mat.iris <- as.matrix(x.iris)
y.mat.iris <- as.matrix(y.iris)
```

```{r, echo=FALSE}
iris.table <- head(cbind(x.iris, y.iris))
dots.row <- as.data.frame(matrix("\\vdots", nrow = 1, ncol = ncol(iris.table)))
colnames(dots.row) <- colnames(iris.table)
iris.table.with.dots <- rbind(iris.table, dots.row)
colnames(iris.table.with.dots) <- gsub("\\.", " ", colnames(iris.table.with.dots))
kable(
  iris.table.with.dots,
  caption = "Iris Dataset (First 6 Observations): Predictors and Responses",
  booktabs = TRUE,
  linesep = "",
  format = "latex",
  align = "c",
  escape = FALSE
) %>%
  kable_styling(
    latex_options = c("HOLD_position", "striped"),
    full_width = FALSE,
    position = "center",
    font_size = 12
  )
```

### Linear Regression Analysis

```{r}
# Fit linear regression model
iris.lm <- lm(Petal.Length ~ Sepal.Length + Sepal.Width, data = iris)
# Model summary table
snazzieR::model.summary.table(iris.lm, caption = "Linear Regression Model Summary")
```

### Model Equation

```{r}
snazzieR::model.equation(iris.lm)
```

### ANOVA Analysis

```{r}
snazzieR::ANOVA.summary.table(iris.lm, caption = "ANOVA Results")
```

### Eigenvalue Analysis

```{r}
# Prepare iris data and standardize
iris.data <- iris[, 1:4]
scaled.data <- as.data.frame(
  lapply(iris.data, function(x) {
    (x - mean(x)) / sd(x)
  })
)
correlation.matrix <- cor(scaled.data)
# Eigenvalue analysis
snazzieR::eigen.summary(correlation.matrix)
```

### PLS Regression (NIPALS)

```{r}
NIPALS.pls.iris <- snazzieR::pls.regression(x.mat.iris, y.mat.iris, n.components = 3, calc.method = "NIPALS")
snazzieR::pls.summary(NIPALS.pls.iris, include.scores = FALSE)
```
